In [1]:
# use emg_env environment to run this code
import tables
import numpy as np
import matplotlib.pyplot as plt
import os
from scipy import signal, fft
import glob


In [2]:
def load_bmi3d_hdf_table(data_dir, filename, table_name):
    '''
    Loads data and metadata from a table in an hdf file generated by BMI3D

    Args:
        data_dir (str): path to the data
        filename (str): name of the file to load from
        table_name (str): name of the table you want to load

    Returns:
        tuple: Tuple containing:
            | **data (ndarray):** data from bmi3d
            | **metadata (dict):** attributes associated with the table
    '''
    filepath = os.path.join(data_dir, filename)
    with tables.open_file(filepath, 'r') as f:
        if table_name not in f.root:
            raise ValueError(f"{table_name} not found in {filename}")
        table = getattr(f.root, table_name)
        param_keys = table.attrs._f_list("user")
        metadata = {k : getattr(table.attrs, k) for k in param_keys}
        return table.read(), metadata

In [3]:
PATH = '/Users/mmadduri/Library/CloudStorage/Box-Box/2024_IMWUT_EMG_FL/User Study/'

In [4]:
keys = ['S100', 
        'S101', 
        'S102', 
        'S103', 
        'S104', 
        'S105', 
        'S106', 
        'S107',
        'S108', 
        'S109', 
        'S110', 
        'S111', 
        'S112', 
        'S113', 
        'S114', 
        'S115',
        'S116',
        'S117', ]

# create dataframe
var_names = ['refs','poss','dec_vels','int_vels','emgs','Ws','Hs','alphas', 'pDs','times','conditions']

## BLOCK 1
targ_block1 = {key: [] for key in keys} # re
curs_block1 = {key: [] for key in keys}
dec_vels_block1 = {key: [] for key in keys}                                            
emgs_block1 = {key: [] for key in keys}
int_vel_block1 = {key: [] for key in keys}
Ws_block1 = {key: [] for key in keys}
# Hs_block1 = {key: [] for key in keys}
# alphas_block1 = {key: [] for key in keys}
# pDs_block1 = {key: [] for key in keys}
times_block1 = {key: [] for key in keys}
conditions_block1 = {key: [] for key in keys}

## BLOCK 2
targ_block2 = {key: [] for key in keys} # re
curs_block2 = {key: [] for key in keys}
dec_vels_block2 = {key: [] for key in keys}
emgs_block2 = {key: [] for key in keys}
int_vel_block2 = {key: [] for key in keys}
Ws_block2 = {key: [] for key in keys}
# Hs_block2 = {key: [] for key in keys}
# alphas_block2 = {key: [] for key in keys}
# pDs_block2 = {key: [] for key in keys}
times_block2 = {key: [] for key in keys}
conditions_block2 = {key: [] for key in keys}
# decoders_block1 = {key: [] for key in keys}

In [ ]:
cond_num = 4 # index of cond
block_num = 3 # index of decoder condition

## BLOCK 1
for key in keys:
    print("subj: ", key)

    subj = key + "/"
    data_dir = PATH + subj # set up path with subject files

    block1_files = []
    # block2_files = []

    for name in glob.glob(data_dir + '/weiner_IMWUT25_' + key + '_Block1*.h5'):
        file_name = os.path.basename(name)
        block1_files.append(file_name)

    # sort files
    block1_files = sorted(block1_files, key = lambda x: x.split("_")[block_num] + x.split("_")[cond_num])

    for file_name in block1_files:
        print("file: ", file_name)
        weiner_task_data, weiner_config = load_bmi3d_hdf_table(data_dir, file_name, 'weiner')
        f = weiner_task_data
        c = weiner_config
        # print(f.dtype.names) # get the names of the fields
        targ_block1[key].append(np.asarray(f['reference']))
        curs_block1[key].append(np.asarray(f['decoded_position']))
        dec_vels_block1[key].append(np.asarray(f['decoded_velocity']))
        int_vel_block1[key].append(np.asarray(f['intended_velocity'])) # didn't seem to be saving
        emgs_block1[key].append(np.asarray(f['filtered_emg']))
        Ws_block1[key].append(np.asarray(f['weiner_filter_w']))
        # Hs_block1[key].append(np.asarray(f['weiner_filter_h'][0]))
        # alphas_block1[key].append(c['alpha'])
        # pDs_block1[key].append(c['lambdaD'])
        time = np.asarray(f['timestamp']).flatten()
        times_block1[key].append(time - time[0])
        conditions_block1[key].append(file_name[27:29])
    


    







subj:  S100
file:  weiner_IMWUT25_S100_Block1_C0_local_random_init.h5
file:  weiner_IMWUT25_S100_Block1_C1_local_prev_local_init.h5
file:  weiner_IMWUT25_S100_Block1_C2_local_sims_init.h5
file:  weiner_IMWUT25_S100_Block1_C3_StaticTrial.h5
file:  weiner_IMWUT25_S100_Block1_C4_pfa_random_init.h5
file:  weiner_IMWUT25_S100_Block1_C5_pfa_sims_init.h5
file:  weiner_IMWUT25_S100_Block1_C6_pfa_running_random.h5
file:  weiner_IMWUT25_S100_Block1_C7_pfa_running_sim.h5
subj:  S101
file:  weiner_IMWUT25_S101_Block1_C0_local_random_init.h5
file:  weiner_IMWUT25_S101_Block1_C1_local_prev_local_init.h5
file:  weiner_IMWUT25_S101_Block1_C2_local_sims_init.h5
file:  weiner_IMWUT25_S101_Block1_C3_StaticTrial.h5
file:  weiner_IMWUT25_S101_Block1_C4_pfa_random_init.h5
file:  weiner_IMWUT25_S101_Block1_C5_pfa_sims_init.h5
file:  weiner_IMWUT25_S101_Block1_C6_pfa_running_random.h5
file:  weiner_IMWUT25_S101_Block1_C7_pfa_running_sim.h5
subj:  S102
file:  weiner_IMWUT25_S102_Block1_C0_local_random_init.h5


: 

In [11]:
targ_block1

{'S100': [array([[ 0.        ,  0.        ],
         [ 0.        ,  0.        ],
         [ 0.        ,  0.        ],
         ...,
         [14.91835429,  7.67086278],
         [14.91835429,  7.67086278],
         [14.91835429,  7.67086278]]),
  array([[ 0.        ,  0.        ],
         [ 0.        ,  0.        ],
         [ 0.        ,  0.        ],
         ...,
         [ 0.04852805, -1.67901435],
         [ 0.04852805, -1.67901435],
         [ 0.04852805, -1.67901435]]),
  array([[ 0.        ,  0.        ],
         [ 0.        ,  0.        ],
         [ 0.        ,  0.        ],
         ...,
         [15.96089012,  3.17252012],
         [15.96089012,  3.17252012],
         [15.96089012,  3.17252012]]),
  array([[ 0.        ,  0.        ],
         [ 0.        ,  0.        ],
         [-0.        ,  0.        ],
         ...,
         [-6.15115441,  2.27677513],
         [-6.15115441,  2.27677513],
         [-6.15115441,  2.27677513]]),
  array([[ 0.        ,  0.        ],
   

In [46]:
# needs to be updated for each run

subj = 'S102/'
key = keys[2]
cond_num = 4 # index of cond
block_num = 3 # index of decoder condition

block1_files = []
block2_files = []

print(PATH)
data_dir = PATH + subj
print(data_dir)


## block 1
for name in glob.glob(data_dir + '/weiner_IMWUT25_' + key + '_Block1*.h5'):
    file_name = os.path.basename(name)
    block1_files.append(file_name)

# sort files
block1_files = sorted(block1_files, key = lambda x: x.split("_")[block_num] + x.split("_")[cond_num])

print(block1_files)


## block 1
for name in glob.glob(data_dir + '/weiner_IMWUT25_' + key + '_Block2*.h5'):
    file_name = os.path.basename(name)
    block2_files.append(file_name)

# sort files
block2_files = sorted(block2_files, key = lambda x: x.split("_")[block_num] + x.split("_")[cond_num])

print(block2_files)

/Users/mmadduri/Library/CloudStorage/Box-Box/2024_IMWUT_EMG_FL/User Study/
/Users/mmadduri/Library/CloudStorage/Box-Box/2024_IMWUT_EMG_FL/User Study/S102/
['weiner_IMWUT25_S102_Block1_C0_local_random_init.h5', 'weiner_IMWUT25_S102_Block1_C1_local_prev_local_init.h5', 'weiner_IMWUT25_S102_Block1_C2_local_sims_init.h5', 'weiner_IMWUT25_S102_Block1_C3_StaticTrial.h5', 'weiner_IMWUT25_S102_Block1_C4_pfa_random_init.h5', 'weiner_IMWUT25_S102_Block1_C5_pfa_sims_init.h5', 'weiner_IMWUT25_S102_Block1_C6_pfa_running_random.h5', 'weiner_IMWUT25_S102_Block1_C7_pfa_running_sim.h5']
['weiner_IMWUT25_S102_Block2_C0_local_random_init.h5', 'weiner_IMWUT25_S102_Block2_C1_local_prev_local_init.h5', 'weiner_IMWUT25_S102_Block2_C2_local_sims_init.h5', 'weiner_IMWUT25_S102_Block2_C3_StaticTrial.h5', 'weiner_IMWUT25_S102_Block2_C4_pfa_random_init.h5', 'weiner_IMWUT25_S102_Block2_C5_pfa_sims_init.h5', 'weiner_IMWUT25_S102_Block2_C6_pfa_running_random.h5', 'weiner_IMWUT25_S102_Block2_C7_pfa_running_sim.h5']


In [47]:
block1_files

['weiner_IMWUT25_S102_Block1_C0_local_random_init.h5',
 'weiner_IMWUT25_S102_Block1_C1_local_prev_local_init.h5',
 'weiner_IMWUT25_S102_Block1_C2_local_sims_init.h5',
 'weiner_IMWUT25_S102_Block1_C3_StaticTrial.h5',
 'weiner_IMWUT25_S102_Block1_C4_pfa_random_init.h5',
 'weiner_IMWUT25_S102_Block1_C5_pfa_sims_init.h5',
 'weiner_IMWUT25_S102_Block1_C6_pfa_running_random.h5',
 'weiner_IMWUT25_S102_Block1_C7_pfa_running_sim.h5']

In [48]:
block2_files

['weiner_IMWUT25_S102_Block2_C0_local_random_init.h5',
 'weiner_IMWUT25_S102_Block2_C1_local_prev_local_init.h5',
 'weiner_IMWUT25_S102_Block2_C2_local_sims_init.h5',
 'weiner_IMWUT25_S102_Block2_C3_StaticTrial.h5',
 'weiner_IMWUT25_S102_Block2_C4_pfa_random_init.h5',
 'weiner_IMWUT25_S102_Block2_C5_pfa_sims_init.h5',
 'weiner_IMWUT25_S102_Block2_C6_pfa_running_random.h5',
 'weiner_IMWUT25_S102_Block2_C7_pfa_running_sim.h5']

In [49]:
data_dir = PATH + subj

In [50]:
for file_name in block1_files:
        print("file: ", file_name)
        weiner_task_data, weiner_config = load_bmi3d_hdf_table(data_dir, file_name, 'weiner')
        f = weiner_task_data
        c = weiner_config
        # print(f.dtype.names) # get the names of the fields
        targ_block1[key].append(np.asarray(f['reference']))
        curs_block1[key].append(np.asarray(f['decoded_position']))
        dec_vels_block1[key].append(np.asarray(f['decoded_velocity']))
        int_vel_block1[key].append(np.asarray(f['intended_velocity'])) # didn't seem to be saving
        emgs_block1[key].append(np.asarray(f['filtered_emg']))
        Ws_block1[key].append(np.asarray(f['weiner_filter_w']))
        # Hs_block1[key].append(np.asarray(f['weiner_filter_h'][0]))
        # alphas_block1[key].append(c['alpha'])
        # pDs_block1[key].append(c['lambdaD'])
        time = np.asarray(f['timestamp']).flatten()
        times_block1[key].append(time - time[0])
        conditions_block1[key].append(file_name[27:29])

for file_name in block2_files:
        print("file: ", file_name)
        weiner_task_data, weiner_config = load_bmi3d_hdf_table(data_dir, file_name, 'weiner')
        f = weiner_task_data
        c = weiner_config
        # print(f.dtype.names) # get the names of the fields
        targ_block2[key].append(np.asarray(f['reference']))
        curs_block2[key].append(np.asarray(f['decoded_position']))
        dec_vels_block2[key].append(np.asarray(f['decoded_velocity']))
        int_vel_block2[key].append(np.asarray(f['intended_velocity'])) # didn't seem to be saving
        emgs_block2[key].append(np.asarray(f['filtered_emg']))
        Ws_block2[key].append(np.asarray(f['weiner_filter_w']))
        # Hs_block1[key].append(np.asarray(f['weiner_filter_h'][0]))
        # alphas_block1[key].append(c['alpha'])
        # pDs_block1[key].append(c['lambdaD'])
        time = np.asarray(f['timestamp']).flatten()
        times_block2[key].append(time - time[0])
        conditions_block2[key].append(file_name[27:29])

# targ_block1[key] = np.asarray(targ_block1[key])
# curs_block1[key] = np.asarray(curs_block1[key])
# dec_vels_block1[key] = np.asarray(dec_vels_block1[key])
# emgs_block1[key] = np.asarray(emgs_block1[key])
# Ws_block1[key] = np.asarray(Ws_block1[key])
# # Hs_block1[key] = np.asarray(Hs_block1[key])
# # alphas_block1[key] = np.asarray(alphas_block1[key])
# # pDs_block1[key] = np.asarray(pDs_block1[key])
# times_block1[key] = np.asarray(times_block1[key])
# conditions_block1[key] = np.asarray(conditions_block1[key])
# int_vel_block1[key] = np.asarray(int_vel_block1[key])

# assert(np.all(conditions_block1[key] == ['C0', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7']) == True)
# assert(len(conditions_block1[key])== 8) 

file:  weiner_IMWUT25_S102_Block1_C0_local_random_init.h5
file:  weiner_IMWUT25_S102_Block1_C1_local_prev_local_init.h5
file:  weiner_IMWUT25_S102_Block1_C2_local_sims_init.h5


: 

In [45]:
targ_block1['S102']

[]

In [39]:
targ_block2['S101']

[array([[ 0.00000000e+00,  0.00000000e+00],
        [ 8.27077290e-05, -8.73946555e-05],
        [ 8.27077290e-05, -8.73946555e-05],
        ...,
        [ 7.16244428e+00, -8.03480330e+00],
        [ 7.16244428e+00, -8.03480330e+00],
        [ 7.16244428e+00, -8.03480330e+00]]),
 array([[  0.        ,   0.        ],
        [  0.        ,   0.        ],
        [  0.        ,   0.        ],
        ...,
        [-16.24674397,   1.17550313],
        [-16.24674397,   1.17550313],
        [-16.24674397,   1.17550313]]),
 array([[ 0.        ,  0.        ],
        [ 0.        ,  0.        ],
        [ 0.        ,  0.        ],
        ...,
        [10.47745167,  5.46975059],
        [10.47745167,  5.46975059],
        [10.47745167,  5.46975059]]),
 array([[-2.87153470e-03, -1.39944841e-03],
        [-2.87153470e-03, -1.39944841e-03],
        [-8.73548011e-03, -4.42920339e-03],
        ...,
        [-1.62359682e+01, -7.33031913e+00],
        [-1.62359682e+01, -7.33031913e+00],
        [-1.62

In [17]:
targ_block1['S100'][0].shape


(18244, 2)

After all are finished

In [ ]:
targ_block1[key] = np.asarray(targ_block1[key])
curs_block1[key] = np.asarray(curs_block1[key])
dec_vels_block1[key] = np.asarray(dec_vels_block1[key])
emgs_block1[key] = np.asarray(emgs_block1[key])
Ws_block1[key] = np.asarray(Ws_block1[key])
# Hs_block1[key] = np.asarray(Hs_block1[key])
# alphas_block1[key] = np.asarray(alphas_block1[key])
# pDs_block1[key] = np.asarray(pDs_block1[key])
times_block1[key] = np.asarray(times_block1[key])
conditions_block1[key] = np.asarray(conditions_block1[key])
int_vel_block1[key] = np.asarray(int_vel_block1[key])

assert(np.all(conditions_block1[key] == ['C0', 'C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7']) == True)
assert(len(conditions_block1[key])== 8) 